name: Auto Update Rules

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 (北京时间 0:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create work directories
        run: |
          mkdir -p work/output
          
      - name: Download latest rules and sing-box
        run: |
          # 下载最新的 geosite.db 和 geoip.db
          curl -L -o work/geosite.db https://github.com/lyc8503/sing-box-rules/releases/latest/download/geosite.db
          curl -L -o work/geoip.db https://github.com/lyc8503/sing-box-rules/releases/latest/download/geoip.db
          
          # 获取最新的 sing-box 版本
          LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          
          # 下载并解压 sing-box
          curl -L -o work/sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
          tar -xzf work/sing-box.tar.gz -C work/
          chmod +x work/sing-box-*/sing-box
          mv work/sing-box-*/sing-box work/
          
      - name: Export rules
        working-directory: work
        run: |
          # 导出 geoip 规则
          ./sing-box geoip export cn -o ./output/geoip-cn.json
          ./sing-box geoip export private -o ./output/geoip-private.json
          
          # 导出 geosite 规则
          ./sing-box geosite export cn -o ./output/geosite-cn.json
          ./sing-box geosite export private -o ./output/geosite-private.json
          ./sing-box geosite export openai -o ./output/geosite-openai.json
          ./sing-box geosite export google-gemini -o ./output/geosite-google-gemini.json
          ./sing-box geosite export geolocation-!cn -o ./output/geosite-geolocation-!cn.json

      - name: Commit and push changes
        run: |
          # 配置 Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 复制生成的文件到仓库根目录
          cp work/output/* .
          
          # 添加、提交并推送更改
          git add .
          git commit -m "Auto update rules $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
