name: Auto Update Rules

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 (北京时间 0:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create work directories
        run: |
          mkdir -p work/output
          
      - name: Download latest rules and sing-box
        run: |
          # 下载最新的 geosite.db 和 geoip.db
          curl -L -o work/geosite.db https://github.com/lyc8503/sing-box-rules/releases/latest/download/geosite.db
          curl -L -o work/geoip.db https://github.com/lyc8503/sing-box-rules/releases/latest/download/geoip.db
                    
          # 下载并解压最新版 sing-box
          LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          curl -L -o work/sing-box-latest.tar.gz https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
          tar -xzf work/sing-box-latest.tar.gz -C work/
          chmod +x work/sing-box-*/sing-box
          mv work/sing-box-*/sing-box work/sing-box-latest

          # 下载并解压 1.8.8 版本的 sing-box
          curl -L -o work/sing-box-1.8.8.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.8.8/sing-box-1.8.8-linux-amd64.tar.gz
          tar -xzf work/sing-box-1.8.8.tar.gz -C work/
          chmod +x work/sing-box-*/sing-box
          mv work/sing-box-*/sing-box work/sing-box-1.8.8

      - name: Export rules with latest version
        working-directory: work
        run: |
          # 使用最新版本导出规则
          ./sing-box-latest geoip export cn -o ./output/geoip-cn.json
          ./sing-box-latest geoip export private -o ./output/geoip-private.json
          ./sing-box-latest geosite export cn -o ./output/geosite-cn.json
          ./sing-box-latest geosite export private -o ./output/geosite-private.json
          ./sing-box-latest geosite export openai -o ./output/geosite-openai.json
          ./sing-box-latest geosite export google-gemini -o ./output/geosite-google-gemini.json
          ./sing-box-latest geosite export geolocation-!cn -o ./output/geosite-geolocation-!cn.json

      - name: Export rules with v1.8.8
        working-directory: work
        run: |
          # 使用 1.8.8 版本导出规则
          mkdir -p output-1.8.8
          ./sing-box-1.8.8 geoip export cn -o ./output-1.8.8/geoip-cn.json
          ./sing-box-1.8.8 geoip export private -o ./output-1.8.8/geoip-private.json
          ./sing-box-1.8.8 geosite export cn -o ./output-1.8.8/geosite-cn.json
          ./sing-box-1.8.8 geosite export private -o ./output-1.8.8/geosite-private.json
          ./sing-box-1.8.8 geosite export openai -o ./output-1.8.8/geosite-openai.json
          ./sing-box-1.8.8 geosite export google-gemini -o ./output-1.8.8/geosite-google-gemini.json
          ./sing-box-1.8.8 geosite export geolocation-!cn -o ./output-1.8.8/geosite-geolocation-!cn.json
          rm -rf geo* sing* 

      - name: Commit and push changes to main branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update rules $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
